export const FETCH_POST = 'FETCH_POST';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const GET_ALL = 'GET_POSTS';
export const GET_ALL_SUCCESS = 'GET_ALL_SUCCESS';
export const GET_ALL_FAILURE = 'GET_ALL_FAILURE';

export const INCREASE_LIKES = 'INCREASE_LIKES';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';

export const WHO_LIKED = 'WHO_LIKED';
export const WHO_LIKED_SUCCESS = 'WHO_LIKED_SUCCESS';
export const WHO_LIKED_FAILURE = 'WHO_LIKED_FAILURE';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const CREATE_USER_IN_STORE = 'CREATE_USER_IN_STORE';
